create table CLIENTES (id bigint generated by default as identity, apellido varchar(255) not null, calle varchar(255), ciudad varchar(255), codigoPostal varchar(255), departamento varchar(255), numero varchar(255), piso varchar(255), provincia varchar(255), email varchar(255), nombre varchar(255) not null, telefono varchar(255), primary key (id));
alter table CUENTAS add constraint FKc40d4u7bpm34omkh7esyo8eac foreign key (titular_Id) references CLIENTES;
alter table MOVIMIENTOS add constraint FK9c0t0b1aadfwqm9fo034mx692 foreign key (cuenta_numero) references CUENTAS;
